In [46]:
import torch

# Load the error analysis data from the saved files
cevae = torch.load('errorcase/cevae.pt')
cet = torch.load('errorcase/cet.pt')

max_mae_diff = -float('inf')
max_mae_diff_data_point = None
cevae_maed_diff = 0
cet_maed_diff = 0

# Initialize variables to track the maximum CEVAE MAE and corresponding data point
max_cevae_mae = -float('inf')
max_cevae_mae_data_point = None

for cevae_entry, cet_entry in zip(cevae, cet):
    mae_diff = cevae_entry['mae_d'] - cet_entry['mae_d']
    if mae_diff > max_mae_diff:
        cevae_maed_diff = cevae_entry['mae_d']
        cet_maed_diff = cet_entry['mae_d']
        max_mae_diff = mae_diff
        max_mae_diff_data_point = cevae_entry
    
    if cevae_entry['mae_d'] > max_cevae_mae:
        max_cevae_mae = cevae_entry['mae_d']
        max_cevae_mae_data_point = cevae_entry

# Extract the data from the data points
cont_tensor_p_diff = max_mae_diff_data_point['cont_tensor_p']
cont_tensor_c_diff = max_mae_diff_data_point['cont_tensor_c']
cat_tensor_p_diff = max_mae_diff_data_point['cat_tensor_p']
cat_tensor_c_diff = max_mae_diff_data_point['cat_tensor_c']
data_len_diff = max_mae_diff_data_point['data_len']
yd_diff = max_mae_diff_data_point['yd']
diff_tensor_diff = max_mae_diff_data_point['diff_tensor']
treatment_diff = max_mae_diff_data_point['treatment']

cont_tensor_p_cevae = max_cevae_mae_data_point['cont_tensor_p']
cont_tensor_c_cevae = max_cevae_mae_data_point['cont_tensor_c']
cat_tensor_p_cevae = max_cevae_mae_data_point['cat_tensor_p']
cat_tensor_c_cevae = max_cevae_mae_data_point['cat_tensor_c']
data_len_cevae = max_cevae_mae_data_point['data_len']
yd_cevae = max_cevae_mae_data_point['yd']
diff_tensor_cevae = max_cevae_mae_data_point['diff_tensor']
treatment_cevae = max_cevae_mae_data_point['treatment']

# Output the results
print("Data point with the highest MAE difference (CEVAE - CET):")
print(f"CEVAE MAE (d): {cevae_maed_diff}")
print(f"CET MAE (d): {cet_maed_diff}")
print(f"MAE difference: {max_mae_diff}")
print("Data point:")
print(f"cont_tensor_p: {cont_tensor_p_diff}")
# print(f"cont_tensor_c: {cont_tensor_c_diff}")
# print(f"cat_tensor_p: {cat_tensor_p_diff}")
# print(f"cat_tensor_c: {cat_tensor_c_diff}")
# print(f"data_len: {data_len_diff}")
# print(f"yd: {yd_diff}")
# print(f"diff_tensor: {diff_tensor_diff}")
# print(f"treatment: {treatment_diff}")

print("\nData point with the highest CEVAE MAE:")
print(f"CEVAE MAE (d): {max_cevae_mae}")
print("Data point:")
print(f"cont_tensor_p: {cont_tensor_p_cevae}")
# print(f"cont_tensor_c: {cont_tensor_c_cevae}")
# print(f"cat_tensor_p: {cat_tensor_p_cevae}")
# print(f"cat_tensor_c: {cat_tensor_c_cevae}")
# print(f"data_len: {data_len_cevae}")
# print(f"yd: {yd_cevae}")
# print(f"diff_tensor: {diff_tensor_cevae}")
# print(f"treatment: {treatment_cevae}")

Data point with the highest MAE difference (CEVAE - CET):
CEVAE MAE (d): 18.583106994628906
CET MAE (d): 3.0463991165161133
MAE difference: 15.536707878112793
Data point:
cont_tensor_p: tensor([[[0.0190, 0.7402, 0.7579],
         [0.0476, 0.2580, 0.2754],
         [0.0190, 0.4394, 0.4563],
         [0.3238, 0.2149, 0.2246],
         [0.5619, 0.2855, 0.2957],
         [0.5619, 0.3870, 0.4060],
         [0.5714, 0.4704, 0.4833],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         

In [44]:
yd_cevae*44 #cluster 1282

tensor([[0.0000, 0.0000],
        [4.6667, 5.0000]])

In [35]:
treatment_cevae

tensor([0.6250, 0.6250])

In [45]:

cat_tensor_p_cevae[1,:,:]

tensor([[ 1.,  0.,  0.,  7., 17.],
        [ 1.,  1.,  0.,  7., 17.],
        [ 1.,  1.,  0.,  7., 17.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  

In [13]:
data_point = max_mae_diff_data_point
cont_tensor_p = data_point[0]
cont_tensor_c = data_point[1]
cat_tensor_p = data_point[2]
cat_tensor_c = data_point[3]
data_len = data_point[4]
yd = data_point[5]
diff_tensor = data_point[6]
treatment = data_point[7]


In [15]:
type(max_mae_diff_data_point[0])

list

In [ ]:
    def __getitem__(self, index):
        '''
            [batch x padding x embedding]
            cont_tensor_p : 패딩이 씌워진 환자 관련 연속 데이터  
            cont_tensor_c : 패딩이 씌워진 클러스터 관련 연속 데이터  
            cat_tensor_p : 패딩이 씌워진 환자 관련 이산 데이터  
            cat_tensor_c : 패딩이 씌워진 클러스터 관련 이산 데이터  
            data_len : 클러스터별 유효 환자수 반환 데이터
            y : 정답 label
            diff_tensor : 클러스터별 유효 날짜 반환 데이터
        '''
        diff_days = torch.from_numpy(self.diff_days[self.cluster == index]).unsqueeze(1)
        diff_tensor = self.diff_tensor.clone()
        diff_tensor[:diff_days.shape[0]] = diff_days
        cont_X = torch.from_numpy(self.cont_X[self.cluster == index])
        data_len = cont_X.shape[0]
        cont_tensor = self.cont_tensor.clone()
        cont_tensor[:cont_X.shape[0],] = cont_X
        cat_X = self.cat_X[self.cluster == index]
        cat_tensor = self.cat_tensor.clone()
        cat_tensor[:cat_X.shape[0],] = cat_X
        cat_tensor_p = cat_tensor[:, :5]
        cat_tensor_c = cat_tensor[:, 5:]
        cont_tensor_p = cont_tensor[:, :3]
        cont_tensor_c = cont_tensor[:, 3:]
        yd = self.yd[index]
        
        treatment = torch.mean(torch.tensor(self.treatment[self.cluster == index]), dim=0) # t1: dis|t2: danger
        return cont_tensor_p, cont_tensor_c, cat_tensor_p, cat_tensor_c, data_len, yd, diff_tensor, treatment